version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 80:3000
    volumes:
      - ./:/code
  mongo:
    image: mongo:4.4.29
    environment:
      MONGO_INITDB_DATABASE: shop
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: